apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: {{ template "fullname" . }}
    spec:
      containers:
      - env:
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST
          value: "kafka-connect"
        - name: BS
          value: "kafka:9092"
        - name: ZK
          value: "kafka-zookeeper:2181"
        - name: SR
          value: "http://schema-registry-schema-registry:8081"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "name" . }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {}
      - env:
        - name: CONNECT_URL
          value: "http://localhost:8083"
        image: "landoop/kafka-connect-ui:latest"
        name: {{ template "name" . }}-ui
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
